import bcryptjs from "bcryptjs";

const salt = await bcryptjs.genSalt(10);
console.log(salt) // $2b$10$b/T.99qxpYBBTR2VYCzrge    $2b : bcryptjs version , $10 : cost factor means how many rounds of hashing will be applied to the password, b/T.99qxpYBBTR2VYCzrge : 22 character random string generated by bcryptjs

const hash = await bcryptjs.hash("password", salt);
console.log(hash)  // $2b$10$nj4pEHXf3UXws5wXQz4EQudzs74HxeoGVF8CrB6lHV4d2UkHe4jt6




//? ---------------------------------------- How to verify a password (Behind the scene) ----------------------------------------------------------------------------


let storePasswordInDB = "$2b$10$nj4pEHXf3UXws5wXQz4EQudzs74HxeoGVF8CrB6lHV4d2UkHe4jt6"

const saltFromDB = storePasswordInDB.substring(0, 29) // $2b$10$nj4pEHXf3UXws5wXQz4EQ

const hashFromDB = storePasswordInDB.substring(29) // udzs74HxeoGVF8CrB6lHV4d2UkHe4jt6

const userInputPassword = "password"

const hashOfUserInputPassword = await bcryptjs.hash(userInputPassword, saltFromDB)
const hashOfUserInputPasswordWithoutSalt = hashOfUserInputPassword.substring(29) // udzs74HxeoGVF8CrB6lHV4d2UkHe4jt6
if(hashOfUserInputPasswordWithoutSalt === hashFromDB){
    console.log("Password is correct", hashOfUserInputPasswordWithoutSalt, hashFromDB)
}else{
    console.log("Password is incorrect", hashOfUserInputPasswordWithoutSalt, hashFromDB)
}


//? ---------------------------------------- How to verify a password (Using bcryptjs built in function) ----------------------------------------------------------------------------

const isPasswordCorrect = await bcryptjs.compare(userInputPassword, storePasswordInDB)
console.log("Is password correct?", isPasswordCorrect)